apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-delete-protection
  namespace: kube-system
data:
  must: |
    - namespace: default
      kinds:
        - Pod
        - Deployment
      label: allowed-for-deletion
    - namespace: "*"
      kinds:
        - Node
      label: allowed-for-deletion
  must-not: |
    - namespace: "*"
      kinds:
        - "*"
      label: protected-against-deletion
