apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodedisruptionbudget
  name: nodedisruptionbudget
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodedisruptionbudget
  strategy: {}
  template:
    metadata:
      labels:
        app: nodedisruptionbudget
    spec:
      containers:
      - name: admission
        image: majeinfo/nodedisruptionbudget:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: admission-certs
          mountPath: /certs
          readOnly: true
      volumes:
      - name: admission-certs
        secret:
          secretName: nodedisruptionbudget-certs
