apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: k8s-delete-protection
  name: k8s-delete-protection
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-delete-protection
  strategy: {}
  template:
    metadata:
      labels:
        app: k8s-delete-protection
    spec:
      containers:
      - name: admission
        image: majetraining/k8s-delete-protection:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8443
        volumeMounts:
        - name: admission-certs
          mountPath: /certs
          readOnly: true
        - name: configmap
          mountPath: "/config"
          readOnly: true
      volumes:
      - name: admission-certs
        secret:
          secretName: k8s-delete-protection-certs
      - name: configmap
        configMap:
          name: k8s-delete-protection
