apiVersion: v1
kind: Secret
metadata:
  name: k8s-delete-protection-certs
  namespace: kube-system
data:
  server-key.pem: $(cat certs/server-key.pem | base64 | tr -d '\n')
  server.pem: $(cat certs/server.crt | base64 | tr -d '\n')

