apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nodedisruptionbudget
  name: nodedisruptionbudget
  namespace: kube-system
spec:
  ports:
  - name: 443-8443
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: nodedisruptionbudget
  type: ClusterIP
