apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-delete-protection
  name: k8s-delete-protection
  namespace: kube-system
spec:
  ports:
  - name: 443-8443
    port: 443
    protocol: TCP
    targetPort: 8443
  selector:
    app: k8s-delete-protection
  type: ClusterIP
