apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}
webhooks:
- name: {{ .Values.serviceName }}.{{ .Values.namespace }}.{{ .Values.clusterDomainName }}
  clientConfig:
    service:
      name: {{ .Values.serviceName }}
      namespace: {{ .Values.namespace }}
      path: "/validate"
    caBundle: {{ .Values.caBundle }}
  rules:
    {{- with .Values.triggerRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  #namespaceSelector:
  #  matchExpressions:
  #  - key: name
  #    operator: In
  #    values: ["default"]
  admissionReviewVersions: ["v1"]
  sideEffects: None
  failurePolicy: {{ .Values.failurePolicy }}
